### ISSUE TITLE
The FSM is not working

### ISSUE THREAD

**Issue by surajkadapa** [acmpesuecc/fsm_1#1]
Using the D flip-flop given, the circuit is not giving the desired output described in the README.

**Comment by JiteshNayak2004** [comment]
heya could i work on this issue

**Comment by Alley2717** [comment]
hey can I work on this

**Comment by surajkadapa** [comment]
@Alley2717 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by kavs2803** [comment]
hey can i be assigned ?

**Comment by Chatter-77** [comment]
Can i get assigned to this issue?

**Comment by Alley2717** [comment]
hey can i get some more time

**Comment by surajkadapa** [comment]
@Alley2717 you are assigned 30 more mins.

**Comment by anshiiJ** [comment]
hey can u assign me this?

**Comment by Alley2717** [comment]
can you please check

**Comment by surajkadapa** [comment]
@Chatter-77 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by shreyahegde26** [comment]
can i get assigned to this?

**Comment by siaa1308** [comment]
hey can I work on this

**Comment by surajkadapa** [comment]
@Chatter-77  you are being reassigned sue to issue already being assigned to you

**Comment by surajkadapa** [comment]
@shreyahegde26 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@shreyahegde26 I am reassigning it because time is out.

**Comment by surajkadapa** [comment]
@siaa1308 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by pratyushsinhaa** [comment]
could i work on this next?

**Comment by samarth777** [comment]
cna you assign me

**Comment by anshiiJ** [comment]
hey can i pls work on it??

**Comment by Mrigank-J** [comment]
is this done or still a work in progress? if it is still a work in progress then i will take it

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by UdayaPragna** [comment]
can you assign me this issue

**Comment by shrxyyya** [comment]
Hii can I please be assigned this issue as I am working on it currently

**Comment by surajkadapa** [comment]
@shrxyyya please come meet me at sem hall 2

**Comment by Mrigank-J** [comment]
can i be assigned to it?

**Comment by surajkadapa** [comment]
@ZeusOp23 come meet me in sem hall 2

**Comment by surajkadapa** [comment]
@shrxyyya Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
The issue has been resolved.
